public class CustomValidationException extends Exception {
    public CustomValidationException(String message) {
        super(message);
    }
}
public class NumberValidator {
    public void validateNumber(int number) throws CustomValidationException {
        if (number < 0) {
            throw new CustomValidationException("Number cannot be negative");
        }
        System.out.println("Number is valid.");
    }
    public static void main(String[] args) {
        NumberValidator validator = new NumberValidator();
        try {
            validator.validateNumber(-5);  // Will throw the exception
        } catch (CustomValidationException e) {
            System.err.println(e.getMessage());
        }
        try {
            validator.validateNumber(10);  // Will pass validation
        } catch (CustomValidationException e) {
        }
    }
}
